C     Shared entry-point validation. IEEE_IS_FINITE avoids arithmetic
C     comparisons that can trap on NaN with -ffpe-trap=invalid.
      LOGICAL FUNCTION PIPE_VALID(N,PO,MO,MINO,DX,DT,THETA,
     & D,A,T,Z,RS,MU,EPS,RTOL,STOL,MAXIT)
      USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
      IMPLICIT NONE
      INTEGER N,MAXIT,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO,DX,DT,THETA
      DOUBLE PRECISION D,A,T,Z,RS,MU,EPS,RTOL,STOL
      PIPE_VALID=.FALSE.
      IF (N.LT.2.OR.N.GT.100.OR.MAXIT.LT.0) RETURN
      IF (.NOT.IEEE_IS_FINITE(MINO)) RETURN
      IF (.NOT.IEEE_IS_FINITE(DX).OR.
     &    .NOT.IEEE_IS_FINITE(DT).OR.
     &    .NOT.IEEE_IS_FINITE(THETA).OR.
     &    .NOT.IEEE_IS_FINITE(D).OR.
     &    .NOT.IEEE_IS_FINITE(A).OR.
     &    .NOT.IEEE_IS_FINITE(T).OR.
     &    .NOT.IEEE_IS_FINITE(Z).OR.
     &    .NOT.IEEE_IS_FINITE(RS).OR.
     &    .NOT.IEEE_IS_FINITE(MU).OR.
     &    .NOT.IEEE_IS_FINITE(EPS).OR.
     &    .NOT.IEEE_IS_FINITE(RTOL).OR.
     &    .NOT.IEEE_IS_FINITE(STOL)) RETURN
      IF (DX.LE.0D0.OR.DT.LE.0D0.OR.D.LE.0D0.OR.
     & A.LE.0D0.OR.T.LE.0D0.OR.Z.LE.0D0.OR.
     & RS.LE.0D0.OR.MU.LE.0D0.OR.EPS.LT.0D0.OR.
     & RTOL.LE.0D0.OR.STOL.LT.0D0.OR.
     & THETA.LT.0D0.OR.THETA.GT.1D0) RETURN
      DO 10 I=0,N
         IF (.NOT.IEEE_IS_FINITE(PO(I))) RETURN
         IF (PO(I).LE.0D0) RETURN
   10 CONTINUE
      DO 20 I=0,N-1
         IF (.NOT.IEEE_IS_FINITE(MO(I))) RETURN
   20 CONTINUE
      PIPE_VALID=.TRUE.
      END
