      PROGRAM ADAPTIVECHECK
      IMPLICIT NONE
      INTEGER N,MAXREC,I,K,INFO,NACC,NREJ,NTOTAL,NNEWTON
      PARAMETER (N=20,MAXREC=4000)
      INTEGER HNIT(0:MAXREC)
      DOUBLE PRECISION PO(0:N),MO(0:N-1),TIME(0:MAXREC)
      DOUBLE PRECISION DTREC(0:MAXREC),HMIN(0:MAXREC)
      DOUBLE PRECISION HOUT(0:MAXREC),HPOUT(0:MAXREC)
      DOUBLE PRECISION HLINE(0:MAXREC),HETA(0:MAXREC)
      DOUBLE PRECISION HBAL(0:MAXREC),HCFL(0:MAXREC)
      DOUBLE PRECISION PI,D,A,T,Z,RS,MU,EPS,DX,THETA
      DOUBLE PRECISION PIN,MINO,RE,FD,COEF,X,CUM,CUMDEF
      DOUBLE PRECISION REYNOLDS_MASS,FRICTION_SJ
      PI=4D0*DATAN(1D0)
      D=1D0
      A=PI*D*D/4D0
      T=288.15D0
      Z=0.9D0
      RS=500D0
      MU=1.1D-5
      EPS=4.5D-5
      DX=100000D0/DBLE(N)
      THETA=0.65D0
      PIN=8D6
      MINO=100D0
      RE=REYNOLDS_MASS(100D0,D,A,MU)
      FD=FRICTION_SJ(RE,EPS,D)
      COEF=FD*Z*RS*T*100D0*100D0/(D*A*A)
      DO 10 I=0,N
         X=DBLE(I)*DX
         PO(I)=DSQRT(PIN*PIN-COEF*X)
   10 CONTINUE
      DO 20 I=0,N-1
         MO(I)=100D0
   20 CONTINUE
      CALL INTEGRATE_TRANSIENT_ADAPTIVE(N,PO,MO,MINO,
     & PIN,100D0,105D0,600D0,3600D0,THETA,DX,D,A,T,Z,RS,
     & MU,EPS,1D-11,1D-12,30,7.5D0,1D-5,120D0,0.01D0,
     & 0D0,0.125D0,20,MAXREC,TIME,DTREC,HMIN,HOUT,
     & HPOUT,HLINE,HNIT,HETA,HBAL,HCFL,NACC,NREJ,NTOTAL,
     & NNEWTON,INFO)
      IF (INFO.NE.0) THEN
         PRINT *, 'FAIL INFO=',INFO
         STOP 1
      ENDIF
      IF (NACC.LT.30.OR.NACC.GT.1000) STOP 2
      IF (DABS(TIME(NACC)-3600D0).GT.1D-8) STOP 3
      CUM=0D0
      CUMDEF=0D0
      DO 30 K=1,NACC
         IF (DTREC(K).LE.0D0) STOP 4
         IF (HETA(K).GT.1.00000001D0) STOP 5
         CUM=CUM+DTREC(K)*(THETA*(HMIN(K)-HOUT(K))+
     &       (1D0-THETA)*(HMIN(K-1)-HOUT(K-1)))
         CUMDEF=CUMDEF+HBAL(K)
         IF (TIME(K-1).LT.600D0-1D-8.AND.
     &       TIME(K).GT.600D0+1D-8) STOP 6
   30 CONTINUE
      IF (DABS((HLINE(NACC)-HLINE(0))-CUM).GT.1D-5)
     & STOP 7
      IF (DABS(CUMDEF).GT.1D-5) STOP 8
      IF (NTOTAL.NE.NACC+NREJ) STOP 9
      PRINT *, 'ADAPTIVE PASS accepted=',NACC,
     & ' rejected=',NREJ,' newton=',NNEWTON
      END
