      PROGRAM INPUT_VALIDATION_CHECK
      USE, INTRINSIC :: IEEE_ARITHMETIC
      IMPLICIT NONE
      INTEGER N,I,INFO,NITER
      PARAMETER (N=4)
      DOUBLE PRECISION PO(0:N),MO(0:N-1),U(2*N+2)
      DOUBLE PRECISION MINO,PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS
      DOUBLE PRECISION RTOL,STOL,BAD
      DO 10 I=0,N
         PO(I)=8D6
   10 CONTINUE
      DO 20 I=0,N-1
         MO(I)=100D0
   20 CONTINUE
      MINO=100D0
      PIN=8D6
      DX=1D3
      DT=10D0
      THETA=0.65D0
      D=1D0
      A=0.7853981633974483D0
      T=288.15D0
      Z=0.9D0
      RS=500D0
      MU=1.1D-5
      EPS=4.5D-5
      RTOL=1D-11
      STOL=1D-12
      BAD=IEEE_VALUE(0D0,IEEE_QUIET_NAN)
      DO 30 I=1,2*N+2
         U(I)=-12345D0
   30 CONTINUE
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.0) STOP 1
      DO 40 I=1,2*N+2
         U(I)=-12345D0
   40 CONTINUE
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,-1,0,
     & U,INFO,NITER)
      IF (INFO.NE.3.OR.NITER.NE.0) STOP 2
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.0) STOP 3
      DO 50 I=1,2*N+2
         U(I)=-12345D0
   50 CONTINUE
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,BAD,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.3.OR.NITER.NE.0) STOP 4
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.0) STOP 5
      DO 60 I=1,2*N+2
         U(I)=-12345D0
   60 CONTINUE
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.0) STOP 6
      PO(2)=BAD
      DO 70 I=1,2*N+2
         U(I)=-12345D0
   70 CONTINUE
      CALL TRANSIENT_STEP(N,PO,MO,MINO,MINO,MINO,PIN,
     & DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,20,0,
     & U,INFO,NITER)
      IF (INFO.NE.3.OR.NITER.NE.0) STOP 7
      DO 80 I=1,2*N+2
         IF (TRANSFER(U(I),0_8).NE.
     &       TRANSFER(-12345D0,0_8)) STOP 8
   80 CONTINUE
      WRITE(*,*) 'INPUT VALIDATION PASS'
      END
