C     M9B.3: entry validation must reject without changing state.
      PROGRAM NEGATIVE_INPUT_CHECK
      USE, INTRINSIC :: IEEE_ARITHMETIC
      IMPLICIT NONE
      INTEGER N,I,INFO,NITER,CASEID,NACC,NREJ,NTOTAL,NNEWTON
      PARAMETER (N=4)
      DOUBLE PRECISION PO(0:N),MO(0:N-1),U(2*N+2)
      DOUBLE PRECISION MINO,PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS
      DOUBLE PRECISION RTOL,STOL,BAD,INF,SENT
      DOUBLE PRECISION TIME(0:4),DTREC(0:4),HMIN(0:4)
      DOUBLE PRECISION HOUT(0:4),HPOUT(0:4),HLINE(0:4)
      DOUBLE PRECISION HETA(0:4),HBAL(0:4),HCFL(0:4)
      DOUBLE PRECISION TS(2),PS(2),QS(2),ATOL(4),RTOLY(4)
      INTEGER HNIT(0:4)
      SENT=-12345D0
      BAD=IEEE_VALUE(0D0,IEEE_QUIET_NAN)
      INF=IEEE_VALUE(0D0,IEEE_POSITIVE_INF)
      PIN=8D6
      DX=1D3
      DT=10D0
      THETA=0.65D0
      D=1D0
      A=0.7853981633974483D0
      T=288.15D0
      Z=0.9D0
      RS=500D0
      MU=1.1D-5
      EPS=4.5D-5
      RTOL=1D-11
      STOL=1D-12
      TS(1)=0D0
      TS(2)=20D0
      PS(1)=PIN
      PS(2)=PIN
      QS(1)=100D0
      QS(2)=100D0
      DO 5 I=1,4
         ATOL(I)=1D-4
         RTOLY(I)=1D-5
    5 CONTINUE
C     Each test resets the state and checks every output sentinel.
      DO 100 CASEID=1,12
         CALL INIT_STATE(N,PO,MO,MINO)
         DO 10 I=1,2*N+2
            U(I)=SENT
   10    CONTINUE
         IF (CASEID.EQ.1) THEN
            CALL TRANSIENT_STEP(1,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.2) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,0D0,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.3) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,BAD,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.4) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       INF,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.5) THEN
            PO(2)=BAD
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.6) THEN
            MO(1)=INF
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.7) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       -1,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.8) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,1.1D0,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
         ELSE IF (CASEID.EQ.9) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
            IF (INFO.NE.0) STOP 19
            U(4)=BAD
            CALL NEWTON_SOLVE(N,U,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,INFO,NITER)
            IF (INFO.NE.3.OR.NITER.NE.0) STOP 20
            IF (.NOT.IEEE_IS_NAN(U(4))) STOP 21
            GOTO 100
         ELSE IF (CASEID.EQ.10) THEN
            CALL NEWTON_SOLVE(N,U,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       -1,0,INFO,NITER)
         ELSE IF (CASEID.EQ.11) THEN
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
            IF (INFO.NE.0) STOP 22
            CALL NEWTON_SOLVE(N,U,PO,MO,MINO,100D0,100D0,
     &       BAD,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,INFO,NITER)
            IF (INFO.NE.3.OR.NITER.NE.0) STOP 23
            GOTO 100
         ELSE
            CALL TRANSIENT_STEP(N,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,U,INFO,NITER)
            IF (INFO.NE.0) STOP 24
            CALL NEWTON_SOLVE(101,U,PO,MO,MINO,100D0,100D0,
     &       PIN,DX,DT,THETA,D,A,T,Z,RS,MU,EPS,RTOL,STOL,
     &       20,0,INFO,NITER)
            IF (INFO.NE.3.OR.NITER.NE.0) STOP 25
            GOTO 100
         ENDIF
         IF (INFO.NE.3.OR.NITER.NE.0) STOP 30
         DO 20 I=1,2*N+2
            IF (TRANSFER(U(I),0_8).NE.TRANSFER(SENT,0_8)) STOP 31
   20    CONTINUE
  100 CONTINUE
C     Fixed-step integrator: invalid argument preserves state/history.
      CALL INIT_STATE(N,PO,MO,MINO)
      CALL FILL_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
      CALL INTEGRATE_TRANSIENT(N,PO,MO,MINO,PIN,100D0,
     & 100D0,10D0,DT,-1,THETA,DX,D,A,T,Z,RS,MU,EPS,
     & RTOL,STOL,20,TIME,HMIN,HOUT,HPOUT,HLINE,HNIT,
     & HCFL(0),INFO)
      IF (INFO.NE.3) STOP 40
      CALL CHECK_STATE(N,PO,MO,MINO)
      CALL CHECK_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
C     Adaptive ramp: invalid DTMIN is rejected before any writes.
      CALL INTEGRATE_TRANSIENT_ADAPTIVE(N,PO,MO,MINO,
     & PIN,100D0,100D0,10D0,20D0,THETA,DX,D,A,T,Z,RS,
     & MU,EPS,RTOL,STOL,20,DT,0D0,DT,1D-2,0D0,0D0,
     & 4,4,TIME,DTREC,HMIN,HOUT,HPOUT,HLINE,HNIT,HETA,
     & HBAL,HCFL,NACC,NREJ,NTOTAL,NNEWTON,INFO)
      IF (INFO.NE.3) STOP 41
      CALL CHECK_STATE(N,PO,MO,MINO)
      CALL CHECK_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
C     Scheduled adaptive: nonfinite schedule rejected pre-write.
      PS(2)=BAD
      CALL INTEGRATE_TRANSIENT_ADAPTIVE_SCHEDULE(N,PO,MO,
     & MINO,2,TS,PS,QS,20D0,THETA,DX,D,A,T,Z,RS,MU,EPS,
     & RTOL,STOL,20,DT,1D0,DT,1D-2,0D0,0D0,4,4,
     & ATOL,RTOLY,TIME,DTREC,HMIN,HOUT,HPOUT,HLINE,
     & HNIT,HETA,HBAL,HCFL,NACC,NREJ,NTOTAL,NNEWTON,INFO)
      IF (INFO.NE.3) STOP 42
      CALL CHECK_STATE(N,PO,MO,MINO)
      CALL CHECK_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
      WRITE(*,*) 'M9B.3 NEGATIVE INPUT PASS'
      END

      SUBROUTINE INIT_STATE(N,PO,MO,MINO)
      IMPLICIT NONE
      INTEGER N,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO
      MINO=100D0
      DO 10 I=0,N
         PO(I)=8D6
   10 CONTINUE
      DO 20 I=0,N-1
         MO(I)=100D0
   20 CONTINUE
      END

      SUBROUTINE CHECK_STATE(N,PO,MO,MINO)
      IMPLICIT NONE
      INTEGER N,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO
      IF (TRANSFER(MINO,0_8).NE.TRANSFER(100D0,0_8)) STOP 50
      DO 10 I=0,N
         IF (TRANSFER(PO(I),0_8).NE.TRANSFER(8D6,0_8)) STOP 51
   10 CONTINUE
      DO 20 I=0,N-1
         IF (TRANSFER(MO(I),0_8).NE.TRANSFER(100D0,0_8)) STOP 52
   20 CONTINUE
      END

      SUBROUTINE FILL_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
      IMPLICIT NONE
      INTEGER I,HNIT(0:*)
      DOUBLE PRECISION TIME(0:*),DTREC(0:*),HMIN(0:*)
      DOUBLE PRECISION HOUT(0:*),HPOUT(0:*),HLINE(0:*)
      DOUBLE PRECISION HETA(0:*),HBAL(0:*),HCFL(0:*),SENT
      DO 10 I=0,4
         TIME(I)=SENT
         DTREC(I)=SENT
         HMIN(I)=SENT
         HOUT(I)=SENT
         HPOUT(I)=SENT
         HLINE(I)=SENT
         HETA(I)=SENT
         HBAL(I)=SENT
         HCFL(I)=SENT
         HNIT(I)=-12345
   10 CONTINUE
      END

      SUBROUTINE CHECK_HISTORY(TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HETA,HBAL,HCFL,HNIT,SENT)
      IMPLICIT NONE
      INTEGER I,HNIT(0:*)
      DOUBLE PRECISION TIME(0:*),DTREC(0:*),HMIN(0:*)
      DOUBLE PRECISION HOUT(0:*),HPOUT(0:*),HLINE(0:*)
      DOUBLE PRECISION HETA(0:*),HBAL(0:*),HCFL(0:*),SENT
      DO 10 I=0,4
         IF (TRANSFER(TIME(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     & TRANSFER(DTREC(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     &       TRANSFER(HMIN(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     & TRANSFER(HOUT(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     &       TRANSFER(HPOUT(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     & TRANSFER(HLINE(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     &       TRANSFER(HETA(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     & TRANSFER(HBAL(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     &       TRANSFER(HCFL(I),0_8).NE.TRANSFER(SENT,0_8).OR.
     & HNIT(I).NE.-12345) STOP 60
   10 CONTINUE
      END
