C     M9C.2a: accepted history survives capacity exhaustion.
      PROGRAM M9CFAIL
      IMPLICIT NONE
      INTEGER N,MAXREC,I,INFO,NACC,NREJ,NTOTAL,NNEWTON
      PARAMETER (N=20,MAXREC=1)
      INTEGER HNIT(0:MAXREC)
      DOUBLE PRECISION PO(0:N),MO(0:N-1),MINO
      DOUBLE PRECISION TIME(0:MAXREC),DTREC(0:MAXREC)
      DOUBLE PRECISION HMIN(0:MAXREC),HOUT(0:MAXREC)
      DOUBLE PRECISION HPOUT(0:MAXREC),HLINE(0:MAXREC)
      DOUBLE PRECISION HETA(0:MAXREC),HBAL(0:MAXREC)
      DOUBLE PRECISION HCFL(0:MAXREC)
      DOUBLE PRECISION TS(2),PS(2),QS(2),ATOL(4),RTOLY(4)
      DOUBLE PRECISION PI,D,A,T,Z,RS,MU,EPS,DX,THETA,PIN
      DOUBLE PRECISION RE,FD,COEF,X,PBASE(0:N),MBASE(0:N-1)
      DOUBLE PRECISION REYNOLDS_MASS,FRICTION_SJ
      PI=4D0*DATAN(1D0)
      D=1D0
      A=PI*D*D/4D0
      T=288.15D0
      Z=0.9D0
      RS=500D0
      MU=1.1D-5
      EPS=4.5D-5
      DX=100000D0/DBLE(N)
      THETA=0.65D0
      PIN=8D6
      RE=REYNOLDS_MASS(100D0,D,A,MU)
      FD=FRICTION_SJ(RE,EPS,D)
      COEF=FD*Z*RS*T*100D0*100D0/(D*A*A)
      DO 10 I=0,N
         X=DBLE(I)*DX
         PBASE(I)=DSQRT(PIN*PIN-COEF*X)
   10 CONTINUE
      DO 20 I=0,N-1
         MBASE(I)=100D0
   20 CONTINUE
      TS(1)=0D0
      TS(2)=3600D0
      PS(1)=PIN
      PS(2)=PIN
      QS(1)=100D0
      QS(2)=105D0
      ATOL(1)=8D6
      ATOL(2)=100D0
      ATOL(3)=5000D0
      ATOL(4)=5D0
      DO 30 I=1,4
         RTOLY(I)=0D0
   30 CONTINUE
C     First run: capacity 1 forces INFO=7 after one acceptance.
      CALL RESET_M9C(N,PO,MO,MINO,PBASE,MBASE)
      CALL INTEGRATE_TRANSIENT_ADAPTIVE(N,PO,MO,MINO,
     & PIN,100D0,105D0,600D0,3600D0,THETA,DX,D,A,T,Z,RS,
     & MU,EPS,1D-11,1D-12,30,7.5D0,1D-5,120D0,0.01D0,
     & 0D0,0.125D0,20,MAXREC,TIME,DTREC,HMIN,HOUT,
     & HPOUT,HLINE,HNIT,HETA,HBAL,HCFL,NACC,NREJ,NTOTAL,
     & NNEWTON,INFO)
      IF (INFO.NE.7.OR.NACC.NE.1) STOP 11
      IF (TIME(1).LE.0D0.OR.TIME(1).GE.3600D0) STOP 12
      IF (DTREC(1).LE.0D0) STOP 13
      IF (NTOTAL.NE.NACC+NREJ) STOP 14
      IF (DABS(MINO-HMIN(1)).GT.1D-12) STOP 15
      IF (DABS(PO(N)-HPOUT(1)).GT.1D-8) STOP 16
C     Initial history must be valid even on capacity failure.
      IF (TRANSFER(TIME(0),0_8).NE.
     &    TRANSFER(0D0,0_8).OR.HNIT(0).NE.0) STOP 17
      PRINT *, 'M9C RAMP CAPACITY PASS'
C     Second run: scheduled adaptive, same capacity contract.
      CALL RESET_M9C(N,PO,MO,MINO,PBASE,MBASE)
      CALL INTEGRATE_TRANSIENT_ADAPTIVE_SCHEDULE(N,PO,MO,
     & MINO,2,TS,PS,QS,3600D0,THETA,DX,D,A,T,Z,RS,MU,EPS,
     & 1D-11,1D-12,30,7.5D0,1D-5,120D0,0.01D0,
     & 0D0,0.125D0,20,MAXREC,ATOL,RTOLY,
     & TIME,DTREC,HMIN,HOUT,HPOUT,HLINE,HNIT,HETA,HBAL,
     & HCFL,NACC,NREJ,NTOTAL,NNEWTON,INFO)
      IF (INFO.NE.7.OR.NACC.NE.1) STOP 21
      IF (TIME(1).LE.0D0.OR.TIME(1).GE.3600D0) STOP 22
      IF (DTREC(1).LE.0D0) STOP 23
      IF (NTOTAL.NE.NACC+NREJ) STOP 24
      IF (DABS(MINO-HMIN(1)).GT.1D-12) STOP 25
      IF (DABS(PO(N)-HPOUT(1)).GT.1D-8) STOP 26
      PRINT *, 'M9C SCHEDULE CAPACITY PASS'
C     DTINIT < DTMIN: HMIN failure before first attempt.
      CALL RESET_M9C(N,PO,MO,MINO,PBASE,MBASE)
      CALL INTEGRATE_TRANSIENT_ADAPTIVE(N,PO,MO,MINO,
     & PIN,100D0,105D0,600D0,3600D0,THETA,DX,D,A,T,Z,RS,
     & MU,EPS,1D-11,1D-12,30,7.5D0,10D0,120D0,0.01D0,
     & 0D0,0.125D0,20,MAXREC,TIME,DTREC,HMIN,HOUT,
     & HPOUT,HLINE,HNIT,HETA,HBAL,HCFL,NACC,NREJ,NTOTAL,
     & NNEWTON,INFO)
      IF (INFO.NE.5.OR.NACC.NE.0) STOP 31
      IF (NTOTAL.NE.0.OR.NREJ.NE.0) STOP 32
      IF (DABS(MINO-100D0).GT.1D-12) STOP 33
      DO 40 I=0,N
         IF (TRANSFER(PO(I),0_8).NE.
     &       TRANSFER(PBASE(I),0_8)) STOP 34
   40 CONTINUE
      PRINT *, 'M9C RAMP HMIN PASS'
      PRINT *, 'M9C.2A FAILURE CONTRACT PASS'
      END

      SUBROUTINE RESET_M9C(N,PO,MO,MINO,PBASE,MBASE)
      IMPLICIT NONE
      INTEGER N,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO
      DOUBLE PRECISION PBASE(0:*),MBASE(0:*)
      DO 10 I=0,N
         PO(I)=PBASE(I)
   10 CONTINUE
      DO 20 I=0,N-1
         MO(I)=MBASE(I)
   20 CONTINUE
      MINO=100D0
      END
