C     M9C.2b: deterministic Newton failure, no state commit.
      PROGRAM M9C2B
      IMPLICIT NONE
      INTEGER N,MAXREC,I,INFO,NACC,NREJ,NTOTAL,NNEWTON
      PARAMETER (N=20,MAXREC=4)
      INTEGER HNIT(0:MAXREC)
      DOUBLE PRECISION PO(0:N),MO(0:N-1),P0(0:N)
      DOUBLE PRECISION MINO,TIME(0:MAXREC),DTREC(0:MAXREC)
      DOUBLE PRECISION HMIN(0:MAXREC),HOUT(0:MAXREC)
      DOUBLE PRECISION HPOUT(0:MAXREC),HLINE(0:MAXREC)
      DOUBLE PRECISION HETA(0:MAXREC),HBAL(0:MAXREC)
      DOUBLE PRECISION HCFL(0:MAXREC),HMAXBAL
      DOUBLE PRECISION TS(2),PS(2),QS(2),ATOL(4),RTOLY(4)
      DOUBLE PRECISION PI,D,A,T,Z,RS,MU,EPS,DX,THETA,PIN
      DOUBLE PRECISION RE,FD,COEF,X
      DOUBLE PRECISION REYNOLDS_MASS,FRICTION_SJ
      PI=4D0*DATAN(1D0)
      D=1D0
      A=PI*D*D/4D0
      T=288.15D0
      Z=0.9D0
      RS=500D0
      MU=1.1D-5
      EPS=4.5D-5
      DX=100000D0/DBLE(N)
      THETA=0.65D0
      PIN=8D6
      RE=REYNOLDS_MASS(100D0,D,A,MU)
      FD=FRICTION_SJ(RE,EPS,D)
      COEF=FD*Z*RS*T*100D0*100D0/(D*A*A)
      DO 10 I=0,N
         X=DBLE(I)*DX
         P0(I)=DSQRT(PIN*PIN-COEF*X)
   10 CONTINUE
      TS(1)=0D0
      TS(2)=100D0
      PS(1)=PIN
      PS(2)=PIN
      QS(1)=100D0
      QS(2)=105D0
      ATOL(1)=8D6
      ATOL(2)=100D0
      ATOL(3)=5000D0
      ATOL(4)=5D0
      DO 20 I=1,4
         RTOLY(I)=0D0
   20 CONTINUE
C     Fixed-step: first solve fails, no physical state change.
      CALL RESET_M9C2B(N,PO,MO,MINO,P0)
      CALL INTEGRATE_TRANSIENT(N,PO,MO,MINO,PIN,100D0,
     & 105D0,0D0,10D0,2,THETA,DX,D,A,T,Z,RS,MU,EPS,
     & 1D-11,1D-12,0,TIME,HMIN,HOUT,HPOUT,HLINE,HNIT,
     & HMAXBAL,INFO)
      IF (INFO.EQ.0) STOP 11
      CALL CHECK_M9C2B(N,PO,MO,MINO,P0)
      IF (TRANSFER(TIME(0),0_8).NE.
     & TRANSFER(0D0,0_8)) STOP 12
      PRINT *, 'M9C FIXED FIRST-STEP FAILURE PASS'
C     Adaptive ramp: MAXREJ=0 terminates after one failure.
      CALL RESET_M9C2B(N,PO,MO,MINO,P0)
      CALL INTEGRATE_TRANSIENT_ADAPTIVE(N,PO,MO,MINO,
     & PIN,100D0,105D0,0D0,100D0,THETA,DX,D,A,T,Z,RS,
     & MU,EPS,1D-11,1D-12,0,10D0,1D-5,20D0,0.01D0,
     & 0D0,0D0,0,MAXREC,TIME,DTREC,HMIN,HOUT,HPOUT,
     & HLINE,HNIT,HETA,HBAL,HCFL,NACC,NREJ,NTOTAL,
     & NNEWTON,INFO)
      IF (INFO.NE.6.OR.NACC.NE.0) STOP 21
      IF (NREJ.NE.1.OR.NTOTAL.NE.1) STOP 22
      CALL CHECK_M9C2B(N,PO,MO,MINO,P0)
      PRINT *, 'M9C RAMP REJECTION LIMIT PASS'
C     Scheduled adaptive: identical failure contract.
      CALL RESET_M9C2B(N,PO,MO,MINO,P0)
      CALL INTEGRATE_TRANSIENT_ADAPTIVE_SCHEDULE(N,PO,MO,
     & MINO,2,TS,PS,QS,100D0,THETA,DX,D,A,T,Z,RS,MU,EPS,
     & 1D-11,1D-12,0,10D0,1D-5,20D0,0.01D0,
     & 0D0,0D0,0,MAXREC,ATOL,RTOLY,
     & TIME,DTREC,HMIN,HOUT,HPOUT,HLINE,HNIT,HETA,HBAL,
     & HCFL,NACC,NREJ,NTOTAL,NNEWTON,INFO)
      IF (INFO.NE.6.OR.NACC.NE.0) STOP 31
      IF (NREJ.NE.1.OR.NTOTAL.NE.1) STOP 32
      CALL CHECK_M9C2B(N,PO,MO,MINO,P0)
      PRINT *, 'M9C SCHEDULE REJECTION LIMIT PASS'
      PRINT *, 'M9C.2B FAILURE CONTRACT PASS'
      END

      SUBROUTINE RESET_M9C2B(N,PO,MO,MINO,P0)
      IMPLICIT NONE
      INTEGER N,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO,P0(0:*)
      DO 10 I=0,N
         PO(I)=P0(I)
   10 CONTINUE
      DO 20 I=0,N-1
         MO(I)=100D0
   20 CONTINUE
      MINO=100D0
      END

      SUBROUTINE CHECK_M9C2B(N,PO,MO,MINO,P0)
      IMPLICIT NONE
      INTEGER N,I
      DOUBLE PRECISION PO(0:*),MO(0:*),MINO,P0(0:*)
      IF (TRANSFER(MINO,0_8).NE.
     & TRANSFER(100D0,0_8)) STOP 41
      DO 10 I=0,N
         IF (TRANSFER(PO(I),0_8).NE.
     &       TRANSFER(P0(I),0_8)) STOP 42
   10 CONTINUE
      DO 20 I=0,N-1
         IF (TRANSFER(MO(I),0_8).NE.
     &       TRANSFER(100D0,0_8)) STOP 43
   20 CONTINUE
      END
